defaults:
  - _self_

paths:
  root: null
  data: ${paths.root}/data
  external: ${paths.data}/external
  interim: ${paths.data}/interim
  processed: ${paths.data}/processed
  raw: ${paths.data}/raw

dataset:
  url: https://github.com/karpathy/ng-video-lecture/raw/master/input.txt
  filename: input.txt